library(tseries)
library(forecast)
library(stats)
library(fGarch)
library(rugarch)
library(zoo)
data1<-read.csv("C:/Users/juanp/OneDrive for Business/tercer semestre/series de tiempo/TIIE.csv", header=T)
attach(data1)
data1
data1$Dólar < -ts(data1$Dólar,start=c(2010,156),end=c(2017,310),frequency=365)
summary(data1)
plot(data1,type="l")
plot(Dólar,type="l")
ddolar<-diff(data1$Dólar)
d2dolar<-diff(ddolar)
summary(ddolar)
summary(d2dolar)
var(Dólar)
var(ddolar)
var(d2dolar)
par(mfrow=c(2,1))
plot(ddolar, type="l")
plot(d2dolar, type="l")
adf.test(Dólar)
adf.test(ddolar)
par(mfrow=c(2,1))
acf(Dólar)
pacf(Dólar)
par(mfrow=c(2,1))
acf(ddolar)
pacf(ddolar)
arima(Dólar,order=c(1,0,0))
auto.arima(Dólar)
auto.arima(ddolar)
arimadolar=arima(Dólar,order=c(0,1,1))
arimadolar
plot(arimadolar$residuals, type="l")
forecast(arimadolar,182)
plot(forecast(arimadolar,60))
